package odsc.com.antmendoza.droolsjbpm.simpletest

import odsc.com.antmendoza.droolsjbpm.model.*;

rule "Person between 25 and 45 is potential client level SILVER"
	salience 100
	activation-group "determineLevelByAge" //make this exclusive
    when
        $person: Person(age >= 25 && age <= 45 )
    then
        insert(new PotencialClient($person, PotencialClient.LEVEL.SILVER));
end


rule "Person older than 18 is  is potential client level BRONZE"
	activation-group "determineLevelByAge" //make this exclusive
    when
        $person: Person(age >= 18 )
    then
        insert(new PotencialClient($person, PotencialClient.LEVEL.BRONZE));
end


rule "PotencialClient with annual income greater than 100K"
    no-loop true
    when
        $potencialClient: PotencialClient($personId : person.id)
        $person: Person(id == $personId , annualIncome > 100000L)

		//Select Person.* from PotencialClient, Person where potencialClient.personId = person.id
   		// and person.annualIncome > 100K

    then
	    delete($potencialClient);
        insert(new PotencialClient($person, PotencialClient.LEVEL.GOLD));
end










    



