package odsc.com.antmendoza.droolsjbpm.simpletest

import odsc.com.antmendoza.droolsjbpm.model.*;





rule "Person between 25 and 45 is client level SILVER"
	//salience 100 // default 0, higher salience  means is evaluated first. 
	activation-group "determineLevelByAge" //the first rule in an activation-group to fire will cancel the other rules' activations,
    when
        $person: Person(age >= 25 && age <= 45 )
    then
        insert(new Client($person, Client.LEVEL.SILVER));
end













rule "Person older than 18 is client level BRONZE"
	activation-group "determineLevelByAge" //the first rule in an activation-group to fire will cancel the other rules' activations,
    when
        $person: Person(age >= 18 )
    then
        insert(new Client($person, Client.LEVEL.BRONZE));
end








rule "Client with annual income greater than 100K become GOLD"
    no-loop true
    when

		//Select Person.* from Client, Person where Client.personId = person.id
   		// and person.annualIncome > 100K

        $client: Client($personId : person.id)
        $person: Person(id == $personId , annualIncome > 100000L)
    then
    	modify ( $client )  { setLevel( Client.LEVEL.GOLD ) }
end










    



